// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: libreoffice/libreoffice.proto
#ifndef GRPC_libreoffice_2flibreoffice_2eproto__INCLUDED
#define GRPC_libreoffice_2flibreoffice_2eproto__INCLUDED

#include "libreoffice/libreoffice.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace libreoffice {

// The greeter service definition.
class Libreoffice final {
 public:
  static constexpr char const* service_full_name() {
    return "libreoffice.Libreoffice";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status Convert(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::libreoffice::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::libreoffice::Response>> AsyncConvert(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::libreoffice::Response>>(AsyncConvertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::libreoffice::Response>> PrepareAsyncConvert(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::libreoffice::Response>>(PrepareAsyncConvertRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void Convert(::grpc::ClientContext* context, const ::libreoffice::Request* request, ::libreoffice::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Convert(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::libreoffice::Response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Convert(::grpc::ClientContext* context, const ::libreoffice::Request* request, ::libreoffice::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Convert(::grpc::ClientContext* context, const ::libreoffice::Request* request, ::libreoffice::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Convert(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::libreoffice::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Convert(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::libreoffice::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::libreoffice::Response>* AsyncConvertRaw(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::libreoffice::Response>* PrepareAsyncConvertRaw(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Convert(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::libreoffice::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::libreoffice::Response>> AsyncConvert(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::libreoffice::Response>>(AsyncConvertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::libreoffice::Response>> PrepareAsyncConvert(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::libreoffice::Response>>(PrepareAsyncConvertRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Convert(::grpc::ClientContext* context, const ::libreoffice::Request* request, ::libreoffice::Response* response, std::function<void(::grpc::Status)>) override;
      void Convert(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::libreoffice::Response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Convert(::grpc::ClientContext* context, const ::libreoffice::Request* request, ::libreoffice::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Convert(::grpc::ClientContext* context, const ::libreoffice::Request* request, ::libreoffice::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Convert(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::libreoffice::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Convert(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::libreoffice::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::libreoffice::Response>* AsyncConvertRaw(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::libreoffice::Response>* PrepareAsyncConvertRaw(::grpc::ClientContext* context, const ::libreoffice::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Convert_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status Convert(::grpc::ServerContext* context, const ::libreoffice::Request* request, ::libreoffice::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Convert() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvert(::grpc::ServerContext* context, ::libreoffice::Request* request, ::grpc::ServerAsyncResponseWriter< ::libreoffice::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Convert<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Convert() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::libreoffice::Request, ::libreoffice::Response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::libreoffice::Request* request, ::libreoffice::Response* response) { return this->Convert(context, request, response); }));}
    void SetMessageAllocatorFor_Convert(
        ::grpc::experimental::MessageAllocator< ::libreoffice::Request, ::libreoffice::Response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::libreoffice::Request, ::libreoffice::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Convert(
      ::grpc::CallbackServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Convert(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Convert<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Convert<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Convert() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Convert() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvert(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Convert() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Convert(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Convert(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Convert(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Convert() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::libreoffice::Request, ::libreoffice::Response>(std::bind(&WithStreamedUnaryMethod_Convert<BaseClass>::StreamedConvert, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::libreoffice::Request* /*request*/, ::libreoffice::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedConvert(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::libreoffice::Request,::libreoffice::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Convert<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Convert<Service > StreamedService;
};

}  // namespace libreoffice


#endif  // GRPC_libreoffice_2flibreoffice_2eproto__INCLUDED
