<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libreoffice/libreoffice.proto

namespace GPBMetadata\Libreoffice;

class Libreoffice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6020a1d6c696272656f66666963652f6c696272656f66666963652e70" .
            "726f746f120b6c696272656f666669636522360a0752657175657374120c" .
            "0a046e616d65180120012809120c0a0474797065180220012809120f0a07" .
            "636f6e74656e7418032001280c223b0a0b46696c65436f6e74656e74120c" .
            "0a046e616d65180120012809120d0a056f72646572180220012805120f0a" .
            "07636f6e74656e7418032001280c22520a08526573706f6e7365120c0a04" .
            "636f6465180120012805120f0a076d65737361676518022001280912270a" .
            "0566696c657318032003280b32182e6c696272656f66666963652e46696c" .
            "65436f6e74656e7432470a0b4c696272656f666669636512380a07436f6e" .
            "7665727412142e6c696272656f66666963652e526571756573741a152e6c" .
            "696272656f66666963652e526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

