<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libreoffice/libreoffice.proto

namespace Libreoffice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>libreoffice.FileContent</code>
 */
class FileContent extends \Google\Protobuf\Internal\Message
{
    /**
     *文件名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *文件顺序
     *
     * Generated from protobuf field <code>int32 order = 2;</code>
     */
    protected $order = 0;
    /**
     *二进制的文件内容
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     */
    protected $content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          文件名
     *     @type int $order
     *          文件顺序
     *     @type string $content
     *          二进制的文件内容
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Libreoffice\Libreoffice::initOnce();
        parent::__construct($data);
    }

    /**
     *文件名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *文件名
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *文件顺序
     *
     * Generated from protobuf field <code>int32 order = 2;</code>
     * @return int
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     *文件顺序
     *
     * Generated from protobuf field <code>int32 order = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkInt32($var);
        $this->order = $var;

        return $this;
    }

    /**
     *二进制的文件内容
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *二进制的文件内容
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->content = $var;

        return $this;
    }

}

