<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libreoffice/libreoffice.proto

namespace Libreoffice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>libreoffice.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     *文件名,可选
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *要转换成的类型,pdf,png/jpg
     *
     * Generated from protobuf field <code>string type = 2;</code>
     */
    protected $type = '';
    /**
     *二进制的文件内容
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     */
    protected $content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          文件名,可选
     *     @type string $type
     *          要转换成的类型,pdf,png/jpg
     *     @type string $content
     *          二进制的文件内容
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Libreoffice\Libreoffice::initOnce();
        parent::__construct($data);
    }

    /**
     *文件名,可选
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *文件名,可选
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *要转换成的类型,pdf,png/jpg
     *
     * Generated from protobuf field <code>string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *要转换成的类型,pdf,png/jpg
     *
     * Generated from protobuf field <code>string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     *二进制的文件内容
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *二进制的文件内容
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->content = $var;

        return $this;
    }

}

